spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_elurah
    username: root
    password: P@ssW0rd32!
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Jakarta
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8081
